### PR TITLE
Add option to permit retaining the original name

### PR DESCRIPTION
**Pull request by kidoman**
Setting `opts.retainName` to true will retain the original file's name. So instead of `390025aef74c5829.png` we will get `atomify-390025aef74c5829.png`

### CODE REVIEW

**Comment by kidoman** [comment]
In ref to #2 cc @bclinkinbeard

**Comment by bclinkinbeard** [comment]
Overall this looks good, a few comments.
- I think we can reuse the fixtures in the `basic` dir rather than adding new ones.
- We should test both states of the option.
- I'm not crazy about the `!!` syntax.

Lastly, I'd like to see what `rework-assets` does before deciding on whether this should default to true or false. Right now I am leaning towards having retain be true by default.

**Comment by kidoman** [comment]
- I think we can reuse the fixtures in the basic dir rather than adding new ones.
  - Should not be a big deal
- We should test both states of the option.
  - Aren't all the other test cases doing that? retainName is false by default
- I'm not crazy about the !! syntax.
  - I thought `!!` was the recommended way of handling the gazillion different ways in which people can specify truthiness

**Comment by bclinkinbeard** [comment]
Implemented as d859783 and published as 1.1.0

**Pull request closed without merging**
